accounts/urls.py
from django.contrib.auth.forms import AuthenticationForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html",
                                                authentication_form=UserLoginForm), name="login"),
    path("password_reset/", auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html",
                                                                 form_class=PwdResetForm), name="pwdreset"),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html', form_class=PwdResetConfirmForm), name="pwdresetconfirm"),
    path("profile/", views.profile, name="profile"),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>/",
         views.activate, name='activate'),

]

bank/urls.py
from . import views
from django.urls import path


app_name = 'bank'

urlpatterns = [
    path('', views.home, name='home'),
    path('form', views.dataform, name='dataform'),
    path('show', views.show, name='show')
]

demo/urls.py
import bank
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bank.urls", namespace='bank')),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    path('accounts/', include("django.contrib.auth.urls")),
]

urlpatterns += staticfiles_urlpatterns()

accounts/models.py
# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3',
                                                             'placeholder': 'Username', 'id': 'login-username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'Password',
                                                                 'id': 'login-pwd', }))


class RegistrationForm(forms.ModelForm):

    username = forms.CharField(
        label='Enter Username', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required',
                             error_messages={'required': 'Sorry, you will need an Email.'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError("Username already exist")
        return username

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords do not match.")
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Please use another Email, this is already taken")
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'E-mail', 'name': 'email', 'id': 'id_email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Repeat Password'})


class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))


class PwdResetForm(PasswordResetForm):

    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'class': 'form-control-mb3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        else:
            raise forms.ValidationError(
                "Please use another Email, this email does not exist.")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.models import User
from .forms import RegistrationForm
from .token import account_activation_token

# Create your views here.


@login_required
def profile(request):
    return render(request, 'accounts/profile.html', {'section': 'profile'})


def account_register(request):
    if request.method == 'POST':
        registerForm = RegistrationForm(request.POST)
        if registerForm.is_valid():
            user = registerForm.save(commit=False)
            user.email = registerForm.cleaned_data['email']
            user.set_password(registerForm.cleaned_data['password'])
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate your Account'
            message = render_to_string('registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject=subject, message=message)
            return HttpResponse('registered succesfully please check your mail for activation link.')
    else:
        registerForm = RegistrationForm()
    return render(request, 'registration/register.html', {'form': registerForm})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('login')
    else:
        return render(request, 'registration/activation_invalid.html')

templates/account.html
{% extends 'base.html' %}

{% block title %}
Account Summary
{% endblock %}

{% block content %}

{% load static %}
<section id="hero" class="hero d-flex align-items-center">

    <div class="container">
        <div class="row">
            <div class="col-lg-6 d-flex flex-column justify-content-center">
                <h1> Account already Exist.</h1>
                <h1 data-aos="fade-up">View Your Data:</h1>
                <button onclick="window.location.href='show'">Continue</button>


</section><!-- End Hero -->

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %}

        {% endblock %}</title>
    <meta content="" name="description">

    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
  * Template Name: FlexStart - v1.6.0
  * Template URL: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

            <a href="{% url 'bank:home' %}" class="logo d-flex align-items-center">
                <img src="{% static 'img/logo.png' %}" alt="">
                <span>OurBank</span>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="{% url 'bank:home' %}">Home</a></li>
                    <li><a class="nav-link scrollto active" href="{% url 'bank:dataform' %}">Account</a></li>

                    {% if not request.user.is_authenticated %}
                    <a class="nav-link scrollto active" href="{% url 'login' %}">Login</a>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <a class="nav-link scrollto active" href="{% url 'logout' %}">Logout</a>
                    {% endif %}
        </div>


        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->

    {% block content %}
    {% endblock %}


    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'vendor/purecounter/purecounter.js' %}"></script>
    <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script>

</body>

</html>

templates/form.html
{% extends 'base.html' %}

{% block title %}
Start Account
{% endblock %}

{% block content %}

{% load static %}

<section id="hero" class="hero d-flex align-items-center">

    <div class="container">
        <div class="row">
            <form action="{% url 'bank:dataform' %}" method="POST">
                {% if form.errors %}
                <div class="alert alert-primary" role="alert">
                    error
                </div>
                {% endif %}

                {% csrf_token %}

                {{ form.as_p }}

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</section>


{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}

{% load static %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="hero d-flex align-items-center">

  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center">
        <h1 data-aos="fade-up">We offer modern solutions for your business</h1>
        <h2 data-aos="fade-up" data-aos-delay="400">We are team of talented developer making banking websites
        </h2>
        <div data-aos="fade-up" data-aos-delay="600">
          <div class="text-center text-lg-start">
            <a href="{% url 'bank:dataform' %}"
              class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
              <span>Get Started</span>
              <i class="bi bi-arrow-right"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
        <img src="{% static 'img/hero-img.png' %}" class="img-fluid" alt="">
      </div>
    </div>
  </div>

</section><!-- End Hero -->

{% endblock %}

templates/show.html
{% extends 'base.html' %}

{% block title %}
Account Summary
{% endblock %}

{% block content %}

{% load static %}
<section id="hero" class="hero d-flex align-items-center">

    <div class="container">
        <div class="row">
            {% if messages %}
            {% for mess in messages %}
            {{mess}}
            <div class="alert alert-warning" role="alert">
                {{mess}}
            </div>
            {% endfor %}
            {% endif %}


            {% if otp %}

            <div class="col-lg-6 d-flex flex-column justify-content-center">
                <h1 data-aos="fade-up">Enter OTP </h1>
            </div>
            <br>
            <form method="POST" action="{% url 'bank:show' %}">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">OTP</span>
                    </div>
                    <input type="text" class="form-control" placeholder="Enter Your OTP" aria-label="OTP"
                        aria-describedby="basic-addon1" name='otp'>
                </div>
                <div class="input-group-prepend">
                    <button class="input-group-text" type="submit">Verify</button>
                    <small class="float-right text-muted"><i><a href="#" class="text-dark"
                                onclick="ReSendOTP('{{usr.username}}', 'resendOTPmess')"><i
                                    id="resendOTPmess">Resend</i> OTP</a></small>
                </div>
            </form>

            {% else %}
            <div class="col-lg-6 d-flex flex-column justify-content-center">
                <h1 data-aos="fade-up">Your Balance </h1>
            </div>
            <br>
            <table>
                <tr>
                    <th>
                        Property
                    </th>
                    <th>
                        Value
                    </th>
                </tr>
                <tr>
                    <td>
                        Name:
                    </td>
                    <td>
                        {{ledger.full_name}}
                    </td>
                </tr>
                <tr>
                    <td>
                        Mobile No:
                    </td>
                    <td>
                        {{ledger.phone}}
                    </td>
                </tr>
                <tr>
                    <td>
                        Email id:
                    </td>
                    <td>
                        {{ledger.email}}
                    </td>
                </tr>
                <tr>
                    <td>
                        Account balance:
                    </td>
                    <td>
                        {{ledger.balance}}
                    </td>
                </tr>
            </table>
            {% endif %}
</section><!-- End Hero -->

{% endblock %}